name: Appenderrors

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check Component
        run: |
          echo "Job 1 started"
          # Simulating an error
          echo "Error: Component not found" >> error_log.txt
          exit 1

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 2 - Check Environment
        run: |
          echo "Job 2 started"
          # Simulating another error
          echo "Error: Environment not found" >> error_log.txt
          exit 1
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Step 3 - Check Environment
        run: |
          echo "Job 3 started"
          # Simulating another error
          echo "Error: Environment not found" >> error_log.txt
          exit 1

  final-notification:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Read error log and send notification
        run: |
          if [[ -f $GITHUB_WORKSPACE/error_log.txt ]]; then
            error_message=$(cat error_log.txt)
            echo "Sending notification with error details..."
            echo "Error details: $error_message"
          else
            echo "No errors occurred"
