name: Appenderrors
on:
  workflow_dispatch:
    inputs:
      COMPONENT:
        description: "Input the component to check (e.g., 'valid_component')"
        required: true
        type: string
        options:
          - sphere
          - saas
      ENVIRONMENT:
        description: "Input the environment to check (e.g., 'prod')"
        required: true
        type: string
        options:
          - prod
          - dev
          - qa
          - uat
        default: "prod"  # Default to "prod" if no value is provided

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check Component
        run: |
          echo "Job 1 started"
          # Simulating an error with if-else
          if [ "${{ inputs.COMPONENT }}" = "valid_component" ]; then
            echo "Component '${{ inputs.COMPONENT }}' is valid"
          else
            echo "Component '${{ inputs.COMPONENT }}' is not valid"
            echo "Error: Component '${{ inputs.COMPONENT }}' not found" >> error_log.txt
            cat error_log.txt
            exit 1
          fi
      
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 2 - Check Environment
        run: |
          echo "Job 2 started"
          # Simulating another error with if-else
          if [ "${{ inputs.ENVIRONMENT }}" = "prod" ]; then
            echo "Environment '${{ inputs.ENVIRONMENT }}' is valid"
          else
            echo "Environment '${{ inputs.ENVIRONMENT }}' is not valid"
            echo "Error: Invalid environment '${{ inputs.ENVIRONMENT }}'" >> error_log.txt
            cat error_log.txt
            exit 1
          fi
     
  final-notification:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Check if there were any errors and send notification
        run: |
          if [[ -f error_log.txt ]]; then
            error_message=$(cat error_log.txt)
            echo "Sending notification with error details..."
            echo "Error details: $error_message"
          else
            echo "No errors occurred"
          fi
