name: APractiseSession workflow
on: 
 workflow_dispatch:
jobs:
  JobNo1:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [linux, ubuntu]
        version: [1.1,1.3]
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
        
      - name: version check
        run: |
          echo "${{matrix.os}}"
          echo "${{matrix.version}}"

        
    #steps: 
      #- name: checkout repo
        #uses: actions/checkout@v3

      #- name: setting the version
        #id: set-version
        #run: echo "version=3.1.1" >> $env:GITHUB_OUTPUT

      #- name: Print the statement
        #run: echo "The version is ${{ steps.set-version.outputs.version}}"

  
        
     
        
