name: APractiseSession workflow
on: 
 workflow_dispatch:
jobs:
  JobNo1:
    runs-on: self-hosted
    outputs:
      env: ${{ steps.set-version.outputs.version }}
    
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setting the version
        id: set-version
        #run: echo "version=3.1.1" >> $env:GITHUB_OUTPUT
        run: |
          echo "env= ./"

      - name: Print the statement
        run: echo "The version is ${{ steps.set-version.outputs.version}}"

  JobNo2:
    runs-on: self-hosted
    needs: JobNo1
    strategy:
      matrix:
        env: ${{needs.JobNo1.outputs.env}}
        #os: [linux, ubuntu]
        #version: [1.1, 1.3]
        #env: [Dev, Staging]
      #max-parallel: 1
      fail-fast: false #continue with other matrix jobs even if one fails
    steps: 
      - name: version check
        run: |
          echo "${{matrix.os}}"
          echo "${{matrix.version}}"       
     
        
