name: Test Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to checkout"
        required: true
        default: main
        type: string

jobs:
  call-reusable:
     uses: mspriya92/terraform_deployment_control/.github/workflows/reusable.yml@main
     with:
        branch: ${{ inputs.branch }}
   #runs-on: ubuntu-latest
   #steps:
     #- name: checkout repo
       #uses: actions/checkout@v4
       #with:
          #repository: mspriya92/terraform_deployment_control
          #ref: ${{ inputs.branch }}
          #path: saas-cd

     #- uses: ./saas-cd/.github/workflows/reusable.yml
       #with:
          #branch: ${{ inputs.branch }}
