name: Calling reusable

on:
  workflow_dispatch:

jobs:
  job1:
  #runs-on: ubuntu-latest
    #uses: octo-org/example-repo/.github/workflows/called-workflow.yml@v1
    #uses: mspriya92/TrainBook1/.github/workflows/Newreusable-workflow.yml@main
    uses: ./.github/workflows/Newreusable.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
