name: Deploy Controller

on:
  workflow_dispatch:

jobs:
  call_deploy_phase:
    #runs-on: ubuntu-latest
    uses: ./.github/workflows/deploy-phase.yml

  finalize_deployment:
    runs-on: ubuntu-latest
    needs: call_deploy_phase
    steps:
      - run: |
          echo "Log1 from deploy phase workflow: ${{ needs.call_deploy_phase.outputs.log1 }}"
          echo "Log2 from deploy phase workflow: ${{ needs.call_deploy_phase.outputs.log2 }}"
          echo "Log3 from deploy phase workflow: ${{ needs.call_deploy_phase.outputs.log3 }}"
          echo "Log4 from deploy phase workflow: ${{ needs.call_deploy_phase.outputs.log4 }}"
          echo "Log5 from deploy phase workflow: ${{ needs.call_deploy_phase.outputs.log5 }}"
          
          if [[ "${{ needs.call_deploy_phase.outputs.error_message }}" == "Something went wrong in component!" ]]; then
            echo "Critical error in deployment, aborting deployment controller."
            exit 1
          fi
