name: Deploy Phase
on:
  workflow_call:
    outputs:
      log1:
        description: "First output from deploy component"
        value: ${{ jobs.call_deploy_workflow.outputs.error1 }}
      log2:
        description: "Second output from deploy component"
        value: ${{ jobs.call_deploy_workflow.outputs.error2 }}
      log3:
        description: "Output from job 3"
        value: ${{ jobs.call_deploy_workflow.outputs.error3 }}
      log4:
        description: "Output from job 4"
        value: ${{ jobs.call_deploy_workflow.outputs.error4 }}
      log5:
        description: "Error message from deploy component"
        value: ${{ jobs.call_deploy_workflow.outputs.error_message }}

jobs:
  call_deploy_workflow:
    #runs-on: ubuntu-latest
    uses: ./.github/workflows/deploy-component.yml

  handle_errors:
    runs-on: ubuntu-latest
    needs: call_deploy_workflow
    steps:
      - name: error handling 
        #id: error-handle
        #uses: ./.github/action/deploy-component.yml
        run: |
          echo "Error1 from deploy component workflow: ${{ needs.call_deploy_workflow.outputs.error1 }}"
          echo "Error2 from deploy component workflow: ${{ needs.call_deploy_workflow.outputs.error2 }}"
          echo "Error3 from deploy component workflow: ${{ needs.call_deploy_workflow.outputs.error3 }}"
          echo "Error4 from deploy component workflow: ${{ needs.call_deploy_workflow.outputs.error4 }}"
          echo "Error Message from deploy component workflow: ${{ needs.call_deploy_workflow.outputs.error_message }}"
          if [[ "${{ needs.call_deploy_workflow.outputs.error_message }}" == "Something went wrong in component!" ]]; then
            echo "Critical error in deployment, failing phase deployment."
            exit 1
          fi
