name: Deploy Phase

on:
  workflow_call:
    outputs:
      firstword:
        description: "The first output from deploy component"
        value: ${{ jobs.call_deploy_workflow.outputs.firstword }}
      secondword:
        description: "The second output from deploy component"
        value: ${{ jobs.call_deploy_workflow.outputs.secondword }}
      error_message:
        description: "Error message from deploy component"
        value: ${{ jobs.call_deploy_workflow.outputs.error_message }}

jobs:
  call_deploy_workflow:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/deploy-component.yml

  handle_errors:
    runs-on: ubuntu-latest
    needs: call_deploy_workflow
    steps:
      - run: |
          echo "First Word: ${{ needs.call_deploy_workflow.outputs.firstword }}"
          echo "Second Word: ${{ needs.call_deploy_workflow.outputs.secondword }}"
          echo "Error Message: ${{ needs.call_deploy_workflow.outputs.error_message }}"
          if [[ "${{ needs.call_deploy_workflow.outputs.error_message }}" == "Something went wrong in component!" ]]; then
            echo "Error occurred in component, failing phase deployment."
            exit 1
          fi
