name: Deploy Phase

on:
  workflow_call:
    outputs:
      firstword: ${{ steps.deploy_component.outputs.firstword }}
      secondword: ${{ steps.deploy_component.outputs.secondword }}
      job3_message: ${{ steps.deploy_component.outputs.job3_message }}
      job4_message: ${{ steps.deploy_component.outputs.job4_message }}
      error_message: ${{ steps.deploy_component.outputs.error_message }}

jobs:
  deploy-single-comp:
    runs-on: ubuntu-latest
    steps:
      - name: Call deploy-component.yml
        uses: ./.github/workflows/deploy-component.yml
        id: deploy_component

  deploy-phase-one:
    runs-on: ubuntu-latest
    needs: deploy-single-comp
    steps:
      - name: Call deploy-component.yml
        uses: ./.github/workflows/deploy-component.yml
        id: deploy_component

  deploy-phase-two:
    runs-on: ubuntu-latest
    needs: deploy-phase-one
    steps:
      - name: Call deploy-component.yml
        uses: ./.github/workflows/deploy-component.yml
        id: deploy_component

  deploy-phase-three:
    runs-on: ubuntu-latest
    needs: deploy-phase-two
    steps:
      - name: Call deploy-component.yml
        uses: ./.github/workflows/deploy-component.yml
        id: deploy_component
