name: Deploy Phase
on:
  workflow_call:
    outputs:
      firstword: ${{ jobs.call_deploy_workflow.outputs.firstword }}
      secondword: ${{ jobs.call_deploy_workflow.outputs.secondword }}
      job3_message: ${{ jobs.call_deploy_workflow.outputs.job3_message }}
      job4_message: ${{ jobs.call_deploy_workflow.outputs.job4_message }}
      error_message: ${{ jobs.call_deploy_workflow.outputs.error_message }}

jobs:
  call_deploy_workflow:
    uses: ./.github/workflows/deploy-component.yml

  deploy:
    runs-on: ubuntu-latest
    needs: call_deploy_workflow
    steps:
      - run: |
          echo "First Word from deploy component: ${{ needs.call_deploy_workflow.outputs.firstword }}"
          echo "Second Word from deploy component: ${{ needs.call_deploy_workflow.outputs.secondword }}"
          echo "Message from job3: ${{ needs.call_deploy_workflow.outputs.job3_message }}"
          echo "Message from job4: ${{ needs.call_deploy_workflow.outputs.job4_message }}"
          echo "Error Message from deploy component: ${{ needs.call_deploy_workflow.outputs.error_message }}"

          if [[ "${{ needs.call_deploy_workflow.outputs.error_message }}" == "Something went wrong in deploy component!" ]]; then
            echo "Critical error in deployment, failing phase deployment."
            exit 1
          fi

