name: Deploy Phase
on:
  workflow_call:
    outputs:
      firstword:
        description: "First output from deploy component"
        value: ${{ jobs.call_deploy_workflow.outputs.firstword }}
      secondword:
        description: "Second output from deploy component"
        value: ${{ jobs.call_deploy_workflow.outputs.secondword }}
      job3_message:
        description: "Output from job 3"
        value: ${{ jobs.call_deploy_workflow.outputs.job3_message }}
      job4_message:
        description: "Output from job 4"
        value: ${{ jobs.call_deploy_workflow.outputs.job4_message }}
      error_message:
        description: "Error message from deploy component"
        value: ${{ jobs.call_deploy_workflow.outputs.error_message }}

jobs:
  call_deploy_workflow:
    #runs-on: ubuntu-latest
    uses: ./.github/workflows/deploy-component.yml

  handle_errors:
    runs-on: ubuntu-latest
    needs: call_deploy_workflow
    steps:
      - run: |
          echo "First Word from deploy component: ${{ needs.call_deploy_workflow.outputs.firstword }}"
          echo "Second Word from deploy component: ${{ needs.call_deploy_workflow.outputs.secondword }}"
          echo "Message from job3: ${{ needs.call_deploy_workflow.outputs.job3_message }}"
          echo "Message from job4: ${{ needs.call_deploy_workflow.outputs.job4_message }}"
          echo "Error Message from deploy component: ${{ needs.call_deploy_workflow.outputs.error_message }}"
          if [[ "${{ needs.call_deploy_workflow.outputs.error_message }}" == "Something went wrong in component!" ]]; then
            echo "Critical error in deployment, failing phase deployment."
            exit 1
          fi
