name: Deploy Component

on:
  workflow_call:
    outputs:
      error1:
        description: "First output from the component"
        value: ${{ jobs.job1.outputs.firstword }}
      error2:
        description: "Second output from the component"
        value: ${{ jobs.job2.outputs.secondword }}
      error3:
        description: "Output from job 3"
        value: ${{ jobs.job3.outputs.message }}
      error4:
        description: "Output from job 4"
        value: ${{ jobs.job4.outputs.message }}
      error_message:
        description: "Error message from job 5"
        value: ${{ jobs.job5.outputs.error_message }}

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      firstword: ${{ steps.step1.outputs.firstword }}
    steps:
      - id: step1
        run: echo "firstword=job1 from deploy component" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    outputs:
      secondword: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step2
        run: echo "secondword=job2 from deploy component" >> $GITHUB_OUTPUT

  job3:
    runs-on: ubuntu-latest
    needs: job2
    outputs:
      message: ${{ steps.step3.outputs.message3 }}
    steps:
      - id: step3
        run: echo "message3=Job 3 ran from deploy component" >> $GITHUB_OUTPUT

  job4:
    runs-on: ubuntu-latest
    needs: job3
    outputs:
      message: ${{ steps.step4.outputs.message4 }}
    steps:
      - id: step4
        run: echo "message4=Job 4 ran from deploy component" >> $GITHUB_OUTPUT

  job5:
    runs-on: ubuntu-latest
    needs: job4
    outputs:
      error_message: ${{ steps.error_step.outputs.error_message }}
    steps:
      - id: error_step
        run: |
          if [ "$ERROR_CONDITION" = "true" ]; then
            echo "error_message=Something went wrong in deploy component!" >> $GITHUB_OUTPUT
          else
            echo "error_message=No errors occurred in deploy component." >> $GITHUB_OUTPUT
          fi
        env:
          ERROR_CONDITION: "true"
