name: FileDownloadfromDiffRepo
 
on:
  workflow_dispatch:
    inputs:
      
      code-repository:
        description: 'Provide Repo name'
        required: true
      code-reference:
        description: 'Provide branch name'
        required: true
      
      
 
jobs:
  update-json:
    runs-on: self-hosted
    
    steps:
      
      
      - name: Using workflow from another repo
        uses: Bhacaz/checkout-files@v2
        with:
          repository: ${{ github.event.inputs.code-repository }}
          branch: ${{ github.event.inputs.code-reference }}
          token: ${{ secrets.PAT_TOKEN }}
          path: staging
          files: |
             nsi.json
             test.ps1
           
      
     
