name: JfrogArtifactPush

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
          
      - name: Set up JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          ./jfrog rt config --url ${{ vars.JFROG_URL }} --user ${{ vars.JFROG_USER }} --apikey ${{ vars.JFROG_API_KEY }}
 
      - name: Upload artifact to JFrog
        run: |
          ./jfrog rt upload "target/*.war" "JVM"
