name: JsonSingleFileDownload
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use'
        required: true
      code-repository:
        description: 'Provide Repo name'
        required: true
      ref:
       description: 'Provide branch name'
       required: true
      token:
       description: 'Provide repo-token'
       required: true
      
jobs:
  update-json:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Checkout entire repository
      uses: actions/checkout@v2
    - name: Download and update nsi.json with secrets
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        prod_API_KEY: ${{ secrets.API_KEY }}
      run: ./Scripts/update_and_encrypt.ps1
    #- name: Checkout files
      #uses: Bhacaz/checkout-files@v2
      #with:
        #files: nsi.json
  
    - name: Using workflow from another repo
      uses: actions/checkout@v4
      with:
       repository: ${{ inputs.code-repository }}
       ref: ${{ inputs.code-reference }}
       token: ${{ inputs.repo_token }}
       path: staging
        
