name: JsonSingleFileDownload
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use'
        required: true
      code-repository:
        description: 'Environment to use'
        required: true
      ref:
       description: 'Environment to use'
       required: true
      token:
       description: 'Environment to use'
       required: true
      
jobs:
  update-json:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Checkout entire repository
      uses: actions/checkout@v2
    #- name: Checkout files
      #uses: Bhacaz/checkout-files@v2
      #with:
        #files: nsi.json
  
    - name: Using workflow from another repo
      uses: actions/checkout@v4
      with:
       repository: ${{ inputs.code-repository }}
       ref: ${{ inputs.code-reference }}
       token: ${{ inputs.repo_token }}
       path: staging
        
