name: Karthi
 
on:
  workflow_dispatch:
 
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_ENV
      - id: step2
        run: echo "test=world" >> $GITHUB_ENV
 
  print_outputs:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Print output1 and output2
        run: |
          echo "Output1: ${{ needs.job1.outputs.output1 }}"
          echo "Output2: ${{ needs.job1.outputs.output2 }}"
