name: Karthick1
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    outputs:
      BUILD_VERSION: ${{ steps.set_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: E:/Githubrun
      - name: Set version
        id: set_version
        run: echo "version=1.2.3" >> $GITHUB_OUTPUT
 
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Print version
        run: |
          echo "Build version: ${{ needs.build.outputs.BUILD_VERSION }}"
