name: practise workflow
on: 
 workflow_dispatch:

jobs:
 Build-App:
  runs-on: self-hosted
  outputs: 
     VERSION: ${{ steps.set-version.outputs.version }}

  steps:
    - name: check out repo
      uses: actions/checkout@v3
      
    - name: Setting up version 
      id: set-version
      run: |
        echo "version=3.1.0" >> $GITHUB_OUTPUT
        echo "::set-output name=version1::3.2.0"
        
    - name: print output in job1
      run: echo "Job1 output is ${{ steps.set-version.outputs.version1 }}"
     
 Deploy-App:
   runs-on: self-hosted
   needs: Build-App

   steps:
     - name: Print statement
       run: echo "The setting output version is ${{ needs.Build-App.outputs.VERSION }}"
      
      
