name: Re-usable-workflow
on: 
  workflow_dispatch:
jobs:
  fetch-and-output-info:
     runs-on: ubuntu-latest
     outputs:
      output1: ${{ steps.read-json.outputs.components }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Read Component.json
         id: read-json
         run: |
           components=$(cat component.json)
           echo "components=$components" >> $GITHUB_OUTPUT

       - name: Fetch commit 
         id: fetch_commit_value
         run: |
            components=$(echo "${{ outputs.output1 }}" | jq -c '.[]')
            echo "components=$components"
         
     
