name: SingleFileDownload
 
on:
  workflow_call:
 
jobs:
  caller-workflow:
  runs-on: self-hosted
  steps:
      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
          files: /Scripts/update_and_encrypt.ps1
      - name: Download and update nsi.json with secrets
        uses: ./.github/workflows/ScriptCalling.yml
        with:
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            prod_API_KEY: ${{ secrets.API_KEY }}
        #run: ./Scripts/update_and_encrypt.ps1
   
        


    
  
  
