name: SingleFileDownload
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use'
        required: true
 
jobs:
  update-json:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Checkout files
      uses: Bhacaz/checkout-files@v2
      with:
        files: nsi.json,/Scripts
 
    - name: Download and update nsi.json with secrets
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        prod_API_KEY: ${{ secrets.API_KEY }}
      run: ./update_and_encrypt.ps1
      shell: powershell
        
