name: Download nsi.json
 
on:
  workflow_dispatch:
 
jobs:
  download-json:
    runs-on: self-hosted  
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Print initial nsi.json content
        run: |
          echo "Initial nsi.json content:"
          cat nsi.json 
 
      - name: Download nsi.json from external source
        run: |
          # Replace with your actual download command
          curl -o nsi.json https://myserver.com/nsi.json
 
      - name: Print downloaded nsi.json content
        run: |
          echo "Downloaded nsi.json content:"
          cat /path/to/nsi.json  # Replace /path/to/nsi.json with actual path
 
      - name: Retrieve secrets
        run: |
          DOCKER_USERNAME=$(jq -r '.DockerUsername' /path/to/nsi.json)
          DOCKER_PASSWORD=$(jq -r '.DockerPassword' /path/to/nsi.json)
          echo "DOCKER_USERNAME: $DOCKER_USERNAME"
          echo "DOCKER_PASSWORD: $DOCKER_PASSWORD"
