name: SphereJsonUpdateNew
 
on:
  workflow_dispatch:
 
jobs:
  update-json:
    runs-on: self-hosted  
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Print initial nsi.json content
        run: |
          echo "Initial nsi.json content:"
          try {
            Get-Content nsi.json
          } catch {
            echo "nsi.json doesnot exist in repo"
          }  
         
      - name: Download nsi.json from external source
        run: |
          echo "Downloading nsi.json from external source"
          curl -o nsi.json https://raw.githubusercontent.com/mspriya92/TrainBook1/main/nsi.json
 
      - name: Print downloaded nsi.json content
        run: |
          echo "Downloaded nsi.json content:"
          cat nsi.json
 
      - name: Update nsi.json with secrets
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Updating nsi.json with secrets"
          jq --arg DOCKER_USERNAME "$DOCKER_USERNAME" --arg DOCKER_PASSWORD "$DOCKER_PASSWORD" \
            '.DockerUsername = $DOCKER_USERNAME | .DockerPassword = $DOCKER_PASSWORD' nsi.json > nsi.tmp; `
           Move-Item -Path nsi.tmp -Destination nsi.json
 
      - name: Print updated nsi.json content
        run: |
          echo "Updated nsi.json content:"
          cat nsi.json
 
