name: SphereJsonUpdateNew
 
on:
  workflow_dispatch:
 
jobs:
  update-json:
    runs-on: self-hosted  
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Print initial nsi.json content
        run: |
          echo "Initial nsi.json content:"
          try {
            Get-Content nsi.json
          } catch {
            Write-Host "nsi.json does not exist in the repository."
          }
        shell: pwsh
 
      - name: Download nsi.json from external source
        run: |
          echo "Downloading nsi.json from external source"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/mspriya92/TrainBook1/main/nsi.json" -OutFile "nsi.json"
        shell: pwsh
 
      - name: Print downloaded nsi.json content
        run: |
          echo "Downloaded nsi.json content:"
          Get-Content nsi.json
        shell: pwsh
 
      - name: Update nsi.json with secrets
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Updating nsi.json with secrets"
          $json = Get-Content nsi.json -Raw | ConvertFrom-Json
          $json.DockerUsername = "$env:DOCKER_USERNAME"
          $json.DockerPassword = "$env:DOCKER_PASSWORD"
          $json | ConvertTo-Json | Set-Content -Path nsi.json
        shell: pwsh
 
      - name: Print updated nsi.json content
        run: |
          echo "Updated nsi.json content:"
          Get-Content nsi.json
        shell: pwsh
 
