name: TakingKeyfromJson
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use'
        required: true
      code-repository:
        description: 'Provide Repo name'
        required: true
 
jobs:
  update-json:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout entire repository
        uses: actions/checkout@v2
 
      - name: Read JSON file
        id: read-json
        run: |
         json=$(Get-Content component.json -Raw)
         code_repository=$(jq '.[0].code-repository' <<< "$json")
         echo "code_repository: $code_repository" >> $GITHUB_ENV
     
