name: TakingKeyfromJson
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use'
        required: true
      code-repository:
        description: 'Provide Repo name'
        required: true
 
jobs:
  update-json:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout entire repository
        uses: actions/checkout@v2
 
      
      - name: Get values from the package.json
        id: packageJson
        uses: RadovanPelka/github-action-json@main
        with:
          path: "component.json" # default value

      - name: Extract branch name
        run: |
          branch_name=$(jq '.[] | select(.Phase == "2") | .Branch' component.json)
          echo "branch_name=$branch_name" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ env.branch_name }}
          fetch-depth: 0
