name: TakingKeyfromJson
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use'
        required: true
      code-repository:
        description: 'Provide Repo name'
        required: true
 
jobs:
  update-json:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout entire repository
        uses: actions/checkout@v2
 
      - name: Install jq
        run: sudo apt-get install jq -y
        shell: bash
 
      - name: Read JSON file
        id: read-json
        run: |
          json=$(cat component.json)
          echo "json=$json" >> $GITHUB_ENV
        shell: bash
 
      - name: Filter value from JSON
        id: filter-json
        run: |
          filtered_value=$(echo ${{ env.json }} | jq -r '.[] | select(.Phase == 2) | .Branch')
          echo "filtered_value=$filtered_value" >> $GITHUB_ENV
        shell: bash
 
      - name: Using workflow from another repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.code-repository }}
          ref: ${{ env.filtered_value }}
          token: ${{ secrets.PAT_TOKEN }}
          path: staging
 
      - name: Download and update nsi.json with secrets
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          prod_API_KEY: ${{ secrets.API_KEY }}
        run: ./Scripts/scriptupdate.ps1
        shell: bash
