name: TakingKeyfromJson
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use'
        required: true
      code-repository:
        description: 'Provide Repo name'
        required: true
 
jobs:
  update-json:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout entire repository
        uses: actions/checkout@v2
 
      - name: Read JSON file
        id: read-json
        shell: pwsh
        run: |
          $json = Get-Content component.json -Raw
          echo "json=$json" | Out-File -FilePath $env:GITHUB_ENV -Append
 
      - name: Filter value from JSON
        id: filter-json
        shell: pwsh
        run: |
          $json = $env:json | ConvertFrom-Json
          $filtered_value = ($json | Where-Object { $_.Phase -eq 2 }).Branch
          echo "filtered_value=$filtered_value" | Out-File -FilePath $env:GITHUB_ENV -Append
 
      - name: Using workflow from another repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.code-repository }}
          ref: ${{ env.filtered_value }}
          token: ${{ secrets.PAT_TOKEN }}
          path: staging
      
