name: TakingKeyfromJson

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use'
        required: true
      code-repository:
        description: 'Provide Repo name'
        required: true

jobs:
  update-json:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
     
      - uses: actions/checkout@v3
      #- name: Install jq
        #run: |
          #sudo apt-get update
          #sudo apt-get install jq -y
   
      - name: List Json value
        run: |
          cat component.json
          branch_name=$(jq -r '.[] | select(.Phase == 2) | .Branch' component.json)
          echo "Filtered branch name: $branch_name"
          
     

