name: TakingKeyfromJson

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use'
        required: true
      code-repository:
        description: 'Provide Repo name'
        required: true

jobs:
  update-json:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
     
      - uses: actions/checkout@v3

      - name: List Json value
        run: |
          content=$(cat component.json)
          phase2Branch=$(jq '.[] | select(.Phase == \'2\') | .Branch' <<< "$content'')
          if [[ -z "$phase2Branch" ]]; then
            echo "::warning::No object with Phase=2 found in component.json"
          else
            echo "::set-output name=phase2Branch::$phase2Branch"
          fi

     

