name: Testworkflow1

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/Testworkflow.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "Output: ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}"
          echo "Error message: ${{ needs.job1.outputs.error_message }}"
         
