name: Test linux job
on:
  workflow_dispatch:

jobs:
  testJob:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: set_var
        run: |
          content=`cat component.json`
          
          echo "::set-output name=packageJson::$content"
        
      - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"
  Job2:
    name: Test2
    runs-on: ubuntu-latest
    steps:
      - name: checking
        run: echo "Checking the dependency"

  Job3:
    name: Test3
    runs-on: ubuntu-latest
    steps:
      - name: checking2
        run: echo "Checking the dependency2"
  
      
