name: Test linux job
on:
  workflow_dispatch:

jobs:
  Trigger:
    name: Trigger job
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: echo "Trigger send"
  Job1:
    name: Test
    needs: Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Test1
        run: echo "Checking Job one"
       
      #- id: set_var
        #run: |
          #content=`cat component.json`
          
          #echo "::set-output name=packageJson::$content"
        
      #- run: |
          #echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"
  Job2:
    name: Test2
    needs: Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Test2
        run: |
          echo "Running Test2 job"

  Notify:
    name: Notify
    needs: [Trigger, Job1, Job2]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Notify job
        run: echo "Sending Notify job"
  
      
