name: TestJava
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Set custom workspace directory
      run: |
        mkdir -p E:/checkout  # Ensure the desired directory exists  
        echo "GITHUB_WORKSPACE=E:/checkout/TrainBook1" >> $GITHUB_ENV 

    - name: Check out repository to custom location
      uses: actions/checkout@v3
      with:
        repository: mspriya92/TrainBook1
        token: ${{ secrets.PAT_TOKEN }}
        clean: true
        fetch-depth: 1
        fetch-tags: false
        lfs: false
        submodules: false
        set-safe-directory: true
    #- uses: actions/checkout@v3
      #with: 
        #path: E:\checkout
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
