name: TestJava
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Create custom workspace directory
      run: |
        mkdir -p E:/checkout  # Ensure the custom directory exists

    - name: Create a symbolic link to the custom directory
      run: |
        # Create a symbolic link from default workspace to custom directory
        mklink /D C:\Users\10443\actions-runner\_work\TrainBook1\TrainBook1 E:\checkout\TrainBook1

    - name: Check out repository to default location
      uses: actions/checkout@v3
      with:
        repository: mspriya92/TrainBook1
        token: ${{ secrets.GITHUB_TOKEN }}
        clean: true
        fetch-depth: 1
        fetch-tags: false
        lfs: false
        submodules: false
        set-safe-directory: true
    #- uses: actions/checkout@v3
      #with: 
        #path: E:\checkout
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
