name: UploadArtifacts
on: 
  workflow_dispatch:

jobs:
  process-component:
    runs-on: self-hosted 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - 

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-app
          path: staging
